import {
    BarChart3,
    Bell,
    CalendarDays,
    Camera,
    Check,
    CloudOff,
    CreditCard,
    Database,
    FileText,
    Globe,
    Languages,
    Lock,
    MapPin,
    MessageSquare,
    Printer,
    QrCode,
    Receipt,
    RefreshCw,
    ScanLine,
    Search,
    ShieldCheck,
    Smartphone,
    Users,
    Wallet,
    Zap,
    type LucideIcon,
} from "lucide-react";

// Project feature icons: the stored value is the key. Shared by the admin
// picker (FeaturesManager) and the public project page; unknown/empty → check.
export const FEATURE_ICONS: Record<string, LucideIcon> = {
    check: Check,
    wallet: Wallet,
    "credit-card": CreditCard,
    receipt: Receipt,
    printer: Printer,
    "map-pin": MapPin,
    camera: Camera,
    "qr-code": QrCode,
    scan: ScanLine,
    search: Search,
    "shield-check": ShieldCheck,
    lock: Lock,
    bell: Bell,
    calendar: CalendarDays,
    users: Users,
    "message-square": MessageSquare,
    "file-text": FileText,
    chart: BarChart3,
    database: Database,
    offline: CloudOff,
    sync: RefreshCw,
    smartphone: Smartphone,
    globe: Globe,
    languages: Languages,
    zap: Zap,
};

export const featureIcon = (key?: string | null): LucideIcon =>
    (key && FEATURE_ICONS[key]) || Check;
